version: "3"
services:
  xpressdb:
    image: "postgres:13"
    container_name: postgres-xpressdb-yadas
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: xpress
      POSTGRES_USER: yadas
      POSTGRES_PASSWORD: yadas
  springbootapp:
    container_name: springboot-postgres-yadas
    image: springboot-postgres-yadas
    build: ./
    depends_on:
      - xpressdb
    ports:
      - 8080:8080

  zookeeper:
    image: "bitnami/zookeeper:3.7.0"
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:2.8.0"
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper







